### ISSUE TITLE
IntoStringError on custom DSP example

### ISSUE THREAD

**Issue by GitGhillie** [lebedec/libfmod#16] opened 2024-07-28 15:27 UTC
Hi! I copied test_dsp_custom from main into my project and it worked until I changed the volume in this line:
`mydsp.set_parameter_float(0, 0.25)?;`
If I change it to something like 0.24 or 0.26 the program errors out with:
```
Running `target/debug/examples/manual_registration`
volume: 0.21
Error: String(IntoStringError { inner: "=\nW>\xb9`", error: Utf8Error { valid_up_to: 4, error_len: Some(1) } })

Process finished with exit code 1
```
Do you see the same? I also tried running cargo test on libfmod itself but I'm getting linker errors even though things work fine on my project (might just need to sleep on this and try again later)

**Comment by lebedec** [comment] 2024-07-29 05:19
Hi! Looks like a string pointer problem. I think there is no connection between `volume` and `Utf8Error`. It just unexpected behaviour because of corrupted memory. I'll try to fix it soon.

The examples of DSP int tests are taken from somewhere in the FMOD documentation, I didn't really delve into their meaning =) If you can provide an example of a real use of DSP, that would help a lot. 

Also, please provide linker errors if they still appear.

**Comment by lebedec** [comment] 2024-07-29 06:32
Primary problem:
Implementation of `Into<ffi::FMOD_DSP_PARAMETER_DESC>` tries to pass  field `description` of String type simple as borrowed &str. It is incorrect. Need to moves the ownership of the data to C via CString.

**Comment by lebedec** [comment] 2024-07-29 07:46
Fixed in `2.206.7`, `2.222.3`

**Closed as completed by lebedec** 2024-07-29 07:46 UTC
Labels: bug

**Comment by GitGhillie** [comment] 2024-07-30 05:00
Awesome, thank you for the quick resolution!

Also, good to see support for the logging version of the libs. I always wondered what those L files were and now I know :sweat_smile: 

>  If you can provide an example of a real use of DSP, that would help a lot.

If you're still curious I'll let you know as soon as I have something up and running

**Comment by lebedec** [comment] 2024-07-30 05:24
> If you're still curious I'll let you know as soon as I have something up and running

Yep, I am interested in this

**Comment by GitGhillie** [comment] 2024-10-05 11:41
Things are going well thanks to your work! See https://github.com/GitGhillie/bevy_phonon and https://www.youtube.com/watch?v=DFIYmiytqAw. Feel free to contact me on Discord (user: ixml) if you want to discuss the implementation for example
